In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

In [4]:
tickers = [
    "AAPL",
    "MSFT",
    "JPM",
    "JNJ",
    "XOM",
    "PG",
    "CAT",
    "NEE"
]

start_date = "2016-01-01"
end_date = "2026-01-01"

In [5]:
data = yf.download(
    tickers,
    start=start_date,
    end=end_date,
    auto_adjust=True,
    progress=False
)

data.head()

Price           Close                                                         \
Ticker           AAPL        CAT        JNJ        JPM       MSFT        NEE
Date
2016-01-04  23.688673  52.891834  74.967804  48.184067  47.680958  19.617605
2016-01-05  23.095049  52.339478  75.281143  48.267372  47.898491  19.808903
2016-01-06  22.643085  51.514877  74.900658  47.570602  47.028397  19.744505
2016-01-07  21.687454  49.741192  74.027733  45.646877  45.392620  19.831635
2016-01-08  21.802120  49.235535  73.236870  44.624413  45.531845  19.920656

Price                                  High             ...       Open  \
Ticker             PG        XOM       AAPL        CAT  ...         PG
Date                                                    ...
2016-01-04  58.231094  49.002312  23.693171  52.961852  ...  58.223662
2016-01-05  58.416855  49.419849  23.801099  53.241885  ...  58.283110
2016-01-06  57.852139  49.008644  23.018598  52.004974  ...  57.710961
2016-01-07  57.346909  48.224201  22.514928  50.970328  ...  57.101708
2016-01-08  56.447826  47.249977  22.285563  50.200173  ...  57.480635

Price                     Volume                                         \
Ticker            XOM       AAPL      CAT       JNJ       JPM      MSFT
Date
2016-01-04  49.027617  270597600  8586900  12722800  25393200  53778000
2016-01-05  48.831518  223164000  6139100   6467200  16566700  34079700
2016-01-06  48.483573  273829600  6639300   7733800  22961500  39518900
2016-01-07  48.116653  324377600  8601500   9433100  27630900  56564900
2016-01-08  48.300115  283192000  8278500   9766700  22373300  48754000

Price
Ticker           NEE        PG       XOM
Date
2016-01-04   7716400  11529800  20400100
2016-01-05   8915200   8133700  11993500
2016-01-06   6983200   9551000  18826900
2016-01-07  12870800  11973900  21263800
2016-01-08  14382000   9676400  19033600

[5 rows x 40 columns]

In [6]:
prices = data["Close"]
prices.head()

Ticker,AAPL,CAT,JNJ,JPM,MSFT,NEE,PG,XOM
Date,,,,,,,,
2016-01-04,23.688673,52.891834,74.967804,48.184067,47.680958,19.617605,58.231094,49.002312
2016-01-05,23.095049,52.339478,75.281143,48.267372,47.898491,19.808903,58.416855,49.419849
2016-01-06,22.643085,51.514877,74.900658,47.570602,47.028397,19.744505,57.852139,49.008644
2016-01-07,21.687454,49.741192,74.027733,45.646877,45.392620,19.831635,57.346909,48.224201
2016-01-08,21.802120,49.235535,73.236870,44.624413,45.531845,19.920656,56.447826,47.249977

In [7]:
prices.shape

(2514, 8)

In [8]:
prices.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2514 entries, 2016-01-04 to 2025-12-31
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAPL    2514 non-null   float64
 1   CAT     2514 non-null   float64
 2   JNJ     2514 non-null   float64
 3   JPM     2514 non-null   float64
 4   MSFT    2514 non-null   float64
 5   NEE     2514 non-null   float64
 6   PG      2514 non-null   float64
 7   XOM     2514 non-null   float64
dtypes: float64(8)
memory usage: 176.8 KB